version: '3.4'

services:
  app:
    build:
      context: .
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${OBC_IMAGE_NAME:-obc}:${OBC_IMAGE_TAG:-development}"
    environment:
      PYLINTHOME: /app/.pylint.d
    volumes:
      - .:/app
